### ISSUE TITLE
starter-pack-rasa-nlu

### ISSUE THREAD

**Issue by vikash044** [RasaHQ/starter-pack-rasa-nlu#1] opened 2018-10-29 12:00 UTC
hi  
i facing such as problem any solution ? (http://localhost:5000/parse)

{
"error": "Invalid parse parameter specified"
}

and also ?(http://localhost:5000/parse?q=hello%20there)

{
"project": "default",
"entities": [],
"intent": {
"confidence": 0.6852470563023119,
"name": "greet"
},
"text": "hello there",
"model": "model_20181026-123523",
"intent_ranking": [
{
"confidence": 0.6852470563023119,
"name": "greet"
},
{
"confidence": 0.1782927244349375,
"name": "affirm"
},
{
"confidence": 0.07256601013379048,
"name": "thank"
},
{
"confidence": 0.04439257040932929,
"name": "bye"
},
{
"confidence": 0.011187696661811092,
"name": "name"
},
{
"confidence": 0.008313942057819792,
"name": "joke"
}
]
}

**Comment by adantoscano** [comment] 2018-11-05 12:15
what's the problem?

**Comment by MetcalfeTom** [comment] 2019-05-09 11:36
I'm going to close this now.  The first error is because you tried to access `/parse` without providing a message in your query to parse.  The second error is intended behaviour for the nlu server.

[More info on the docs](https://rasa.com/docs/nlu/http/#endpoints)

**Closed by MetcalfeTom** 2019-05-09 11:36 UTC

**Comment by l2009312042** [comment] 2019-07-02 08:55
Error: Requested URL / not found
run the code  rasa  run   and  access  http://localhost:5000/，i met the error above
